## LOWERCASE CONVERSION

In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('IMDB_movies.csv')

In [23]:
df

                                                    text sentiment
0      My daughter liked it but I was aghast, that a ...       neg
1      I... No words. No words can describe this. I w...       neg
2      this film is basically a poor take on the old ...       neg
3      This is a terrible movie, and I'm not even sur...       neg
4      First of all this movie is a piece of reality ...       pos
...                                                  ...       ...
24995  For one thing, he produced this movie. It has ...       neg
24996  The title comes from an alteration an adolesce...       pos
24997  Christopher Nolan's first film is a 'no budget...       pos
24998  The story is shortly about the faith-lacking b...       neg
24999  I found parts of this movie rather slow, espec...       pos

[25000 rows x 2 columns]

In [12]:
df['text'][3].lower()

"this is a terrible movie, and i'm not even sure why it's so terrible. it's ugly, for one, with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product. the film retains the story and songs that made the stage version of the musical such a hit, but the songs sound lifeless on screen. but mostly, the movie sucks because of the wan performance of lucille ball, who you'd think would be able to make something of this larger-than-life character if anyone could. she sleepwalks through the movie like a terrified actress choking on her opening night, and the film sinks with her. even bea arthur, who i bet was hilarious in the best friend role onstage, can't breathe any life into this stinker.<br /><br />avoid at all costs.<br /><br />grade: d"

In [13]:
df['text'] = df['text'].str.lower()

In [14]:
df.head(5)

                                                text sentiment
0  my daughter liked it but i was aghast, that a ...       neg
1  i... no words. no words can describe this. i w...       neg
2  this film is basically a poor take on the old ...       neg
3  this is a terrible movie, and i'm not even sur...       neg
4  first of all this movie is a piece of reality ...       pos

## REMOVING HTML TAGS

On finding the html tag we use the regular expression - <.*?>

In [15]:
import re ## regular expression

In [16]:
def remove_html_tags(data):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', data)

In [18]:
remove_html_tags(df['text'][3])

"this is a terrible movie, and i'm not even sure why it's so terrible. it's ugly, for one, with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product. the film retains the story and songs that made the stage version of the musical such a hit, but the songs sound lifeless on screen. but mostly, the movie sucks because of the wan performance of lucille ball, who you'd think would be able to make something of this larger-than-life character if anyone could. she sleepwalks through the movie like a terrified actress choking on her opening night, and the film sinks with her. even bea arthur, who i bet was hilarious in the best friend role onstage, can't breathe any life into this stinker.avoid at all costs.grade: d"

In [20]:
df['text'] = df['text'].apply(remove_html_tags)

In [21]:
df.head(5)

                                                text sentiment
0  my daughter liked it but i was aghast, that a ...       neg
1  i... no words. no words can describe this. i w...       neg
2  this film is basically a poor take on the old ...       neg
3  this is a terrible movie, and i'm not even sur...       neg
4  first of all this movie is a piece of reality ...       pos

## Removing URLS

In [22]:
def remove_urls(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [23]:
text = "Check https://google.com and https://openai.com"

In [24]:
remove_urls(text)

'Check  and '

In [25]:
urls = re.findall(r'https?://\S+', text)

In [26]:
urls

['https://google.com', 'https://openai.com']

## Removing Punctuations

In [27]:
import string

In [30]:
punc = string.punctuation

In [31]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
def removing_punct(text):
    for char in punc:
        text = text.replace(char, '')
    return text

In [36]:
df['text'][3]

"this is a terrible movie, and i'm not even sure why it's so terrible. it's ugly, for one, with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product. the film retains the story and songs that made the stage version of the musical such a hit, but the songs sound lifeless on screen. but mostly, the movie sucks because of the wan performance of lucille ball, who you'd think would be able to make something of this larger-than-life character if anyone could. she sleepwalks through the movie like a terrified actress choking on her opening night, and the film sinks with her. even bea arthur, who i bet was hilarious in the best friend role onstage, can't breathe any life into this stinker.avoid at all costs.grade: d"

In [37]:
removing_punct(df['text'][3])

'this is a terrible movie and im not even sure why its so terrible its ugly for one with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product the film retains the story and songs that made the stage version of the musical such a hit but the songs sound lifeless on screen but mostly the movie sucks because of the wan performance of lucille ball who youd think would be able to make something of this largerthanlife character if anyone could she sleepwalks through the movie like a terrified actress choking on her opening night and the film sinks with her even bea arthur who i bet was hilarious in the best friend role onstage cant breathe any life into this stinkeravoid at all costsgrade d'

In [41]:
def rem_punct(text):
    return text.translate(str.maketrans('', '', punc)) ## Much faster than above...

In [42]:
df['text'][3]

"this is a terrible movie, and i'm not even sure why it's so terrible. it's ugly, for one, with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product. the film retains the story and songs that made the stage version of the musical such a hit, but the songs sound lifeless on screen. but mostly, the movie sucks because of the wan performance of lucille ball, who you'd think would be able to make something of this larger-than-life character if anyone could. she sleepwalks through the movie like a terrified actress choking on her opening night, and the film sinks with her. even bea arthur, who i bet was hilarious in the best friend role onstage, can't breathe any life into this stinker.avoid at all costs.grade: d"

In [43]:
rem_punct(df['text'][3])

'this is a terrible movie and im not even sure why its so terrible its ugly for one with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product the film retains the story and songs that made the stage version of the musical such a hit but the songs sound lifeless on screen but mostly the movie sucks because of the wan performance of lucille ball who youd think would be able to make something of this largerthanlife character if anyone could she sleepwalks through the movie like a terrified actress choking on her opening night and the film sinks with her even bea arthur who i bet was hilarious in the best friend role onstage cant breathe any life into this stinkeravoid at all costsgrade d'

## Chat Word Treatement

In [44]:
chat_slang_dict = {
    "u": "you",
    "ur": "your",
    "r": "are",
    "y": "why",
    "b4": "before",
    "gr8": "great",
    "l8r": "later",
    "btw": "by the way",
    "idk": "i don't know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "lol": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "lmao": "laughing my ass off",
    "omg": "oh my god",
    "ttyl": "talk to you later",
    "brb": "be right back",
    "afk": "away from keyboard",
    "np": "no problem",
    "thx": "thanks",
    "ty": "thank you",
    "yw": "you're welcome",
    "pls": "please",
    "plz": "please",
    "bc": "because",
    "cuz": "because",
    "coz": "because",
    "smh": "shaking my head",
    "tbh": "to be honest",
    "fyi": "for your information",
    "irl": "in real life",
    "jk": "just kidding",
    "dm": "direct message",
    "msg": "message",
    "wtf": "what the f***",
    "wth": "what the hell",
    "asap": "as soon as possible",
    "nvm": "never mind",
    "bff": "best friends forever",
    "ily": "i love you",
    "xoxo": "hugs and kisses",
    "gg": "good game",
    "noob": "beginner",
    "op": "overpowered",
    "idc": "i don't care",
    "ikr": "i know right",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "hbu": "how about you",
    "gm": "good morning",
    "gn": "good night"
}

In [49]:
def chat_word_treatment(text):
    new_text = []
    for w in text.split():
        if w.lower() in chat_slang_dict:
            new_text.append(chat_slang_dict[w.lower()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [50]:
text = 'imho he is the best'

In [51]:
chat_word_treatment(text)

'in my humble opinion he is the best'

## Incorrect Spell Treatement

In [6]:
statement = 'hello !!, i am goig to schol'

In [7]:
!pip install textblob

Requirement already satisfied: textblob in c:\users\abhay\anaconda3\lib\site-packages (0.20.0)
Requirement already satisfied: nltk>=3.9 in c:\users\abhay\anaconda3\lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in c:\users\abhay\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in c:\users\abhay\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\abhay\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\abhay\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\abhay\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)

In [8]:
from textblob import TextBlob

In [9]:
TextBlob(statement).correct().string

'hello !!, i am going to school'

## Removing Stop Words

In [10]:
from nltk.corpus import stopwords

In [14]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abhay\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [15]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [26]:
def removing_stop_words(text):
    next_word = []
    for word in text.split():
        if word in stopwords.words('english'):
            next_word.append('')
        else:
            next_word.append(word)
    x = next_word[:]
    next_word.clear()
    return " ".join(x)

In [27]:
df['text'][3].lower()

"this is a terrible movie, and i'm not even sure why it's so terrible. it's ugly, for one, with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product. the film retains the story and songs that made the stage version of the musical such a hit, but the songs sound lifeless on screen. but mostly, the movie sucks because of the wan performance of lucille ball, who you'd think would be able to make something of this larger-than-life character if anyone could. she sleepwalks through the movie like a terrified actress choking on her opening night, and the film sinks with her. even bea arthur, who i bet was hilarious in the best friend role onstage, can't breathe any life into this stinker.<br /><br />avoid at all costs.<br /><br />grade: d"

In [28]:
removing_stop_words(df['text'][3].lower())

"   terrible movie,    even sure    terrible.  ugly,  one,   trendy 1970s visual style  maybe seemed like  good idea   time    enables one  instantly recognize  film   time period    70s product.  film retains  story  songs  made  stage version   musical   hit,   songs sound lifeless  screen.  mostly,  movie sucks    wan performance  lucille ball,   think would  able  make something   larger-than-life character  anyone could.  sleepwalks   movie like  terrified actress choking   opening night,   film sinks  her. even bea arthur,   bet  hilarious   best friend role onstage, can't breathe  life   stinker.<br /><br />avoid   costs.<br /><br />grade: "

## Handling Emoji's

In [36]:
## Handling the emojis by removing the emojis from the text..

import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons 😀
        "\U0001F300-\U0001F5FF"  # symbols & pictographs 🌍
        "\U0001F680-\U0001F6FF"  # transport 🚗
        "\U0001F700-\U0001F77F"  # alchemical symbols
        "\U0001F780-\U0001F7FF"  # geometric shapes
        "\U0001F800-\U0001F8FF"  # supplemental arrows
        "\U0001F900-\U0001F9FF"  # supplemental symbols 🤖
        "\U0001FA00-\U0001FA6F"  # chess symbols
        "\U0001FA70-\U0001FAFF"  # extended symbols
        "\U00002702-\U000027B0"  # dingbats ✂️
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [37]:
text = "Hurry!! Your account is blocked 😡🔥 Click here 👉 http://fake.com"
clean = remove_emojis(text)

print(clean)

Hurry!! Your account is blocked  Click here  http://fake.com

In [38]:
! pip install emoji

Requirement already satisfied: emoji in c:\users\abhay\anaconda3\lib\site-packages (2.15.0)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)

In [39]:
## Handling the emojis by putting there meaning in the sentence..
import emoji

In [40]:
print(emoji.demojize("Hurry!! Your account is blocked 😡🔥 Click here 👉 http://fake.com"))

Hurry!! Your account is blocked :enraged_face::fire: Click here :backhand_index_pointing_right: http://fake.com

## Tokenization

In [41]:
## 1. Split function for tokenization

In [43]:
## Word Tokenization..
df['text'][3].lower().split()

['this',
 'is',
 'a',
 'terrible',
 'movie,',
 'and',
 "i'm",
 'not',
 'even',
 'sure',
 'why',
 "it's",
 'so',
 'terrible.',
 "it's",
 'ugly,',
 'for',
 'one,',
 'with',
 'that',
 'trendy',
 '1970s',
 'visual',
 'style',
 'that',
 'maybe',
 'seemed',
 'like',
 'a',
 'good',
 'idea',
 'at',
 'the',
 'time',
 'but',
 'which',
 'now',
 'enables',
 'one',
 'to',
 'instantly',
 'recognize',
 'a',
 'film',
 'from',
 'that',
 'time',
 'period',
 'as',
 'being',
 'a',
 '70s',
 'product.',
 'the',
 'film',
 'retains',
 'the',
 'story',
 'and',
 'songs',
 'that',
 'made',
 'the',
 'stage',
 'version',
 'of',
 'the',
 'musical',
 'such',
 'a',
 'hit,',
 'but',
 'the',
 'songs',
 'sound',
 'lifeless',
 'on',
 'screen.',
 'but',
 'mostly,',
 'the',
 'movie',
 'sucks',
 'because',
 'of',
 'the',
 'wan',
 'performance',
 'of',
 'lucille',
 'ball,',
 'who',
 "you'd",
 'think',
 'would',
 'be',
 'able',
 'to',
 'make',
 'something',
 'of',
 'this',
 'larger-than-life',
 'character',
 'if',
 'anyone',
 'could.',
 'she',
 'sleepwalks',
 'through',
 'the',
 'movie',
 'like',
 'a',
 'terrified',
 'actress',
 'choking',
 'on',
 'her',
 'opening',
 'night,',
 'and',
 'the',
 'film',
 'sinks',
 'with',
 'her.',
 'even',
 'bea',
 'arthur,',
 'who',
 'i',
 'bet',
 'was',
 'hilarious',
 'in',
 'the',
 'best',
 'friend',
 'role',
 'onstage,',
 "can't",
 'breathe',
 'any',
 'life',
 'into',
 'this',
 'stinker.<br',
 '/><br',
 '/>avoid',
 'at',
 'all',
 'costs.<br',
 '/><br',
 '/>grade:',
 'd']

In [44]:
## Sentence Tokenization
df['text'][3].lower().split('.')

["this is a terrible movie, and i'm not even sure why it's so terrible",
 " it's ugly, for one, with that trendy 1970s visual style that maybe seemed like a good idea at the time but which now enables one to instantly recognize a film from that time period as being a 70s product",
 ' the film retains the story and songs that made the stage version of the musical such a hit, but the songs sound lifeless on screen',
 " but mostly, the movie sucks because of the wan performance of lucille ball, who you'd think would be able to make something of this larger-than-life character if anyone could",
 ' she sleepwalks through the movie like a terrified actress choking on her opening night, and the film sinks with her',
 " even bea arthur, who i bet was hilarious in the best friend role onstage, can't breathe any life into this stinker",
 '<br /><br />avoid at all costs',
 '<br /><br />grade: d']

In [47]:
## 2. By regular Expression
import re
token = re.findall("[\w']+", df['text'][3].lower())
token

# more better than split function

['this',
 'is',
 'a',
 'terrible',
 'movie',
 'and',
 "i'm",
 'not',
 'even',
 'sure',
 'why',
 "it's",
 'so',
 'terrible',
 "it's",
 'ugly',
 'for',
 'one',
 'with',
 'that',
 'trendy',
 '1970s',
 'visual',
 'style',
 'that',
 'maybe',
 'seemed',
 'like',
 'a',
 'good',
 'idea',
 'at',
 'the',
 'time',
 'but',
 'which',
 'now',
 'enables',
 'one',
 'to',
 'instantly',
 'recognize',
 'a',
 'film',
 'from',
 'that',
 'time',
 'period',
 'as',
 'being',
 'a',
 '70s',
 'product',
 'the',
 'film',
 'retains',
 'the',
 'story',
 'and',
 'songs',
 'that',
 'made',
 'the',
 'stage',
 'version',
 'of',
 'the',
 'musical',
 'such',
 'a',
 'hit',
 'but',
 'the',
 'songs',
 'sound',
 'lifeless',
 'on',
 'screen',
 'but',
 'mostly',
 'the',
 'movie',
 'sucks',
 'because',
 'of',
 'the',
 'wan',
 'performance',
 'of',
 'lucille',
 'ball',
 'who',
 "you'd",
 'think',
 'would',
 'be',
 'able',
 'to',
 'make',
 'something',
 'of',
 'this',
 'larger',
 'than',
 'life',
 'character',
 'if',
 'anyone',
 'could',
 'she',
 'sleepwalks',
 'through',
 'the',
 'movie',
 'like',
 'a',
 'terrified',
 'actress',
 'choking',
 'on',
 'her',
 'opening',
 'night',
 'and',
 'the',
 'film',
 'sinks',
 'with',
 'her',
 'even',
 'bea',
 'arthur',
 'who',
 'i',
 'bet',
 'was',
 'hilarious',
 'in',
 'the',
 'best',
 'friend',
 'role',
 'onstage',
 "can't",
 'breathe',
 'any',
 'life',
 'into',
 'this',
 'stinker',
 'br',
 'br',
 'avoid',
 'at',
 'all',
 'costs',
 'br',
 'br',
 'grade',
 'd']

In [61]:
## 3. by Libraries
from nltk.tokenize import word_tokenize, sent_tokenize
token1 = sent_tokenize(df['text'][3].lower())
token2 = word_tokenize(df['text'][3].lower())

In [63]:
!pip install spacy

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\abhay\anaconda3\Lib\site-packages)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001EEE7D93380>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/spacy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001EEE7DE51D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/spacy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001EEE7DE5450>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/spacy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001EEE7DE56D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/spacy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001EEE7DE5950>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/spacy/
ERROR: Could not find a version that satisfies the requirement spacy (from versions: none)
ERROR: No matching distribution found for spacy